# site settings

title: janhenrik
description: home
taglong: Jan Henrik Gundelsby
tagshort: gundelsby.com
url: https://gundelsby.com
baseurl: ""
permalink: pretty
repo: https://github.com/janhenrik/janhenrik.github.io

# author settings

author:
  name: Jan Henrik Gundelsby
  email: janhenrik@gundelsby.com
photo: /assets/jpg/avatar.png

# social media links

social:
  github: janhenrik
  instagram: janhenrik
  linkedin: janhenrikgundelsby
  twitter: janhenrik

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
